
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, ttk


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/menu_med")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1260x725")
window.configure(bg = "#FFFFFF")

#Funcion para abrir otro formulario
import os
def ejecutar_Script():  
    os.system('reporte.py')
    print('Abriendo menu...')


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 725,
    width = 1260,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

#Aqui va el boton para volver al frame anterior
canvas.place(x = 0, y = 0)
bt_imagen_volver = PhotoImage(
    file=relative_to_assets("button_1.png"))
bt_volver = Button(
    image=bt_imagen_volver,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
    bg = "White"
)
bt_volver.place(
    x=21.0,
    y=26.0,
    width=61.0,
    height=60.0
)

canvas.create_rectangle(
    561.0,
    302.0,
    1189.0,
    480.0,
    fill="#EEF8FF",
    outline="")



canvas.create_text(
    720.0,
    177.0,
    anchor="nw",
    text="Estatura",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

#Aqui va el texbox para la estatura
txb_estatura = Entry(
    bd=1,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
txb_estatura.place(
    x=640.0,
    y=233.0,
    width=165.0,
    height=35.0
)

#Aqui va el combobox para especificar si la estatura esta dado en Metros o Pies
cb_estatura = ttk.Combobox(
  state = "readonly",
  values = ["Metros","Pies"]
)
cb_estatura.place(
    x=820.0,
    y=234.0,
    width=59.0,
    height=35.0
)


canvas.create_text(
    990.0,
    177.0,
    anchor="nw",
    text="Peso",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

#Aqui va el Texbox para el peso
txb_peso = Entry(
    bd=1,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
txb_peso.place(
    x=900.0,
    y=234.0,
    width=178.0,
    height=34.0
)

#Aqui va el combobox para especificar si el peso esta dado en lb o kg
cb_peso = ttk.Combobox(
  state = "readonly",
  values = ["Kg","Lb"]
)
cb_peso.place(
    x=1090.0,
    y=234.0,
    width=59.0,
    height=35.0
)

#Aqui va el textbox para el parametro medido

txb_parametro = Entry(
    bd=1,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
txb_parametro.place(
    x=561.0,
    y=554.0,
    width=289.0,
    height=55.0
)

canvas.create_text(
    570.0,
    510.0,
    anchor="nw",
    text="Parámetro medido:",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

#Aqui va el boton para comenzar una medicion
bt_imagen_comenzar = PhotoImage(
    file=relative_to_assets("button_2.png"))
bt_comenzar = Button(
    image=bt_imagen_comenzar,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat",
    bg = "White"
)
bt_comenzar.place(
    x=1060.0,
    y=488.0,
    width=61.65789794921875,
    height=66.0
)

#Aqui va el boton para limpiar y elegir otra medicion
bt_imagen_limpiar = PhotoImage(
    file=relative_to_assets("button_3.png"))
bt_limpiar = Button(
    image=bt_imagen_limpiar,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat",
    bg = "White"
)
bt_limpiar.place(
    x=1122.0,
    y=491.0,
    width=67.0,
    height=71.71826171875
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    61.0,
    image=image_image_1
)

#Aqui va el boton para iniciar medicion de saturacion de oxigeno 
bt_imagen_saturacion_oxigeno = PhotoImage(
    file=relative_to_assets("button_4.png"))
bt_saturacion_oxigeno = Button(
    image=bt_imagen_saturacion_oxigeno,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat",
    bg = "White"
)
bt_saturacion_oxigeno.place(
    x=-10.0,
    y=289.0,
    width=483.0,
    height=90.0
)

#Aqui va el boton para iniciar medicion de presion arterial 
bt_imagen_presion_arterial = PhotoImage(
    file=relative_to_assets("button_5.png"))
bt_presion_arterial = Button(
    image=bt_imagen_presion_arterial,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat",
    bg = "White"
)
bt_presion_arterial.place(
    x=-10.0,
    y=405.0,
    width=484.0,
    height=97.0
)
#Aqui va el boton para la medicion de frecuencia cardiaca
bt_imagen_frecuencia_cardiaca = PhotoImage(
    file=relative_to_assets("button_6.png"))
bt_frecuencia_cardiaca = Button(
    image=bt_imagen_frecuencia_cardiaca,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat",
    bg = "White"
)
bt_frecuencia_cardiaca.place(
    x=-10.0,
    y=522.0,
    width=471.0,
    height=92.0
)


#Aqui va el boton para la medicion de la temperatura
bt_imagen_temperatura = PhotoImage(
    file=relative_to_assets("button_7.png"))
bt_temperatura = Button(
    image=bt_imagen_temperatura,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat",
    bg = "White"
)
bt_temperatura.place(
    x=-25.0,
    y=180.0,
    width=518.0,
    height=93.0
)

#Aqui va el boton
bt_imagen_generar_informe = PhotoImage(
    file=relative_to_assets("button_8.png"))
bt_generar_informe = Button(
    image=bt_imagen_generar_informe,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: ejecutar_Script(),
    relief="flat",
    bg = "White"
)
bt_generar_informe.place(
    x=838.0,
    y=646.0,
    width=424.0,
    height=91.0
)
window.resizable(False, False)
window.mainloop()
