
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, ttk, Canvas, Entry, Text, Button, PhotoImage, HORIZONTAL, StringVar, Label


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Miguel Ángel Ramírez\OneDrive - INTEC\Escritorio\Monitor-Fisiologico\Monitor-Fisiologico\interfaces\assets\reporte_med")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

# class ReporteMed():
#     def __init__(self, medicion, sujeto):


window = Tk()
window.geometry("1260x725")
window.configure(bg="#FFFFFF")

canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=725,
    width=1260,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)

img_regresar = PhotoImage(
    file=relative_to_assets("button_1.png"))
btn_regresar = Button(
    image=img_regresar,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
    bg="white"
)
btn_regresar.place(
    x=50.0,
    y=16.0,
    width=61.0,
    height=60.0
)
# LINEA DIVISORIA ENTRE LOGO Y TITULO INFORME
canvas.create_rectangle(
    49.0,
    95.93429565429688,
    1196.0,
    97.0,
    fill="gray",
    outline="")
# LINEA DIVISORIA ENTRE DATOS SUJETO Y MEDIDAS PARAMETROS
canvas.create_rectangle(
    47.0,
    322.0,
    1196.0,
    325.0,
    fill="#000000",
    outline="")

img_logo = PhotoImage(
    file=relative_to_assets("logo1.png"))
logo1 = canvas.create_image(
    1070.0,
    70.0,
    image=img_logo
)

canvas.create_text(
    50.0,
    120.0,
    anchor="nw",
    text="INFORME DE MEDICIÓN",
    fill="#000000",
    font=("RobotoRoman Regular", 30 * -1)
)

# -- CAMPOS DEL SUJETO --
#Ordenados por label (Nombres:) y luego textbox (Ricardo Jose).

#NOMBRES
canvas.create_text(
    50.0,
    195.0,
    anchor="nw",
    text="Nombre : ",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_nombre = Label(
    window,
    text="",
    bd=0,
    bg="#F5F5F5",
    fg="#000716",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_nombre.place(
    x=177.0,
    y=198.0,
    width=388.0,
    height=34.0
)

#SEXO
canvas.create_text(
    900.0,
    198.0,
    anchor="nw",
    text="Sexo :",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_sexo = Label(
    window,
    text = "",
    bd=0,
    bg="#F5F5F5",
    fg="#000716",
    font=("RobotoRoman Regular", 25 * -1)
    )
lbl_sexo.place(
    x= 985.0,
    y= 198.0,
    width=108.0,
    height=34.0
)

#EDAD
canvas.create_text(
    600,
    195.0,
    anchor="nw",
    text="Edad : ",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

lbl_edad=Label(
    window,
    text="",
    bd=0,
    bg="#F5F5F5",
    fg="#000716",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_edad.place(
    x=707.6485595703125,
    y=198.0,
    width=108.0,
    height=34.0
)

#PESO
canvas.create_text(
    600,
    242.60400390625,
    anchor="nw",
    text="Peso :",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_peso = Label(
    window,
    text="",
    bd=0,
    bg="#F5F5F5",
    fg="#000716",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_peso.place(
    x=707.6485595703125,
    y=247.0,
    width=108.0,
    height=34.0
)

#ESTATURA
canvas.create_text(
    862.0,
    247.0,
    anchor="nw",
    text="Estatura :",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

lbl_estatura = Label(
    window,
    text="",
    bd=0,
    bg="#F5F5F5",
    fg="#000716",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_estatura.place(
    x=985.0,
    y=247.0,
    width=108.0,
    height=34.0
)

#FECHA DE EMISION
canvas.create_text(
    685.0,
    122.0,
    anchor="nw",
    text="Fecha de emisión :",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_fecha = Label(
    window,
    text="",
    bd=0,
    bg="#F5F5F5",
    fg="#000716",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_fecha.place(
    x=946.0,
    y=122.0,
    width=250.0,
    height=34.0
)

#CODIGO DOCUMENTO
lbl_cod_doc = Label(
    window,
    text="",
    bd=0,
    bg="#F5F5F5",
    fg="#000716",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_cod_doc.place(
    x=50.0,
    y=247.0,
    width=515.0,
    height=34.0
)
#-- PARAMETROS FISIOLOGICOS --
#region TITULOS COLUMNAS
canvas.create_text(
    50.0,
    359.0,
    anchor="nw",
    text="Parámetro Fisiológico",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)
canvas.create_text(
    400.0,
    359.0,
    anchor="nw",
    text="Valor",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)
canvas.create_text(
    600.0,
    361.0,
    anchor="nw",
    text="Escala",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)
#endregion

#region TEMPERATURA
canvas.create_text(
    162.0,
    424.0,
    anchor="nw",
    text="Temperatura",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)
#aqui se colocara el textbox con el valor de la temperatura
lbl_temperatura = Label(
    window,
    text = "",
    bd=0,
    bg="#F5F5F5",
    fg="#000716",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_temperatura.place(
    x=379.0,
    y=417.0,
    width=96.0,
    height=34.0
)
#Aqui se colora el progress bar para la escala de la temperatura
TROUGH_COLOR = '#F5F5F5'
BAR_COLOR = 'red'
sty = ttk.Style()
sty.theme_use('clam')
sty.configure("bar.Horizontal.TProgressbar", troughcolor=TROUGH_COLOR,
                bordercolor=TROUGH_COLOR, background=BAR_COLOR, lightcolor=BAR_COLOR,
                darkcolor=BAR_COLOR)


pb_temperatura = ttk.Progressbar(window, orient=HORIZONTAL, mode='determinate', style="bar.Horizontal.TProgressbar")
pb_temperatura.place(
    x=527.0,
    y=415.0,
    width=224.0,
    height=34.0
)
def fill_progress_temp():
    return 50
pb_temperatura['value'] =  fill_progress_temp()


#endregion

#region SATURACION DE OXIGENO
canvas.create_text(
    56.0,
    489.0,
    anchor="nw",
    text="Saturación de Oxígeno",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)
#aqui se colocara el textbox que contiene el valor de la saturacion de oxigeno
lbl_saturacion_oxigeno = Label(
    window,
    text = "",
    bd=0,
    bg="#F5F5F5",
    fg="#000716",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_saturacion_oxigeno.place(
    x=379.0,
    y=480.0,
    width=96.0,
    height=34.0
)
#Aqui se colocara el progress bar para la escala de saturacion de oxigeno
TROUGH_COLOR = '#F5F5F5'
BAR_COLOR = 'red'
sty = ttk.Style()
sty.theme_use('clam')
sty.configure("bar.Horizontal.TProgressbar", troughcolor=TROUGH_COLOR,
                bordercolor=TROUGH_COLOR, background=BAR_COLOR, lightcolor=BAR_COLOR,
                darkcolor=BAR_COLOR)


pb_saturacion_oxigeno = ttk.Progressbar(window, orient=HORIZONTAL, mode='determinate', style="bar.Horizontal.TProgressbar")
pb_saturacion_oxigeno.place(
    x=527.0,
    y=478.0,
    width=224.0,
    height=34.0
)
def fill_progress_saturacion_oxigeno():
    return 50
pb_saturacion_oxigeno['value'] =  fill_progress_saturacion_oxigeno()

#endregion

#region PRESION ARTERIAL
canvas.create_text(
    137.0,
    549.0,
    anchor="nw",
    text="Presión Arterial ",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

#aqui va el textbox del valor correspondiente a la presion arterial
lbl_presion_arterial = Label(
    window,
    text = "",
    bd=0,
    bg="#F5F5F5",
    fg="#000716",
    font=("RobotoRoman Regular", 25 * -1)
)

lbl_presion_arterial.place(
    x=379.0,
    y=540.0,
    width=96.0,
    height=34.0
)

#aqui va el progress bar de la presion arterial

TROUGH_COLOR = '#F5F5F5'
BAR_COLOR = 'red'
sty = ttk.Style()
sty.theme_use('clam')
sty.configure("bar.Horizontal.TProgressbar", troughcolor=TROUGH_COLOR,
                bordercolor=TROUGH_COLOR, background=BAR_COLOR, lightcolor=BAR_COLOR,
                darkcolor=BAR_COLOR)

pb_presion_arterial = ttk.Progressbar(window, orient=HORIZONTAL, mode='determinate', style="bar.Horizontal.TProgressbar")
pb_presion_arterial.place(
    x=527.0,
    y=538.0,
    width=224.0,
    height=34.0
)
def fill_progress_presion_arterial():
    return 50
pb_presion_arterial['value'] =  fill_progress_presion_arterial()
#####################

#endregion


#region FRECUENCIA CARDIACA
canvas.create_text(
    70.0,
    608.0,
    anchor="nw",
    text="Frecuencia Cardiaca ",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

#aqui va el valor correspondiente a la medicion de la frecuencia cardiaca
lbl_frecuencia_cardiaca = Label(
    window,
    text = "",
    bd=0,
    bg="#F5F5F5",
    fg="#000716",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_frecuencia_cardiaca.place(
    x=379.0,
    y=597.0,
    width=96.0,
    height=34.0
)
#aqui debe ir el progress bar para colocar la frecuencia cardiaca

TROUGH_COLOR = '#F5F5F5'
BAR_COLOR = 'red'
sty = ttk.Style()
sty.theme_use('clam')
sty.configure("bar.Horizontal.TProgressbar", troughcolor=TROUGH_COLOR,
                bordercolor=TROUGH_COLOR, background=BAR_COLOR, lightcolor=BAR_COLOR,
                darkcolor=BAR_COLOR)


pb_frecuencia_cardiaca = ttk.Progressbar(window, orient=HORIZONTAL, mode='determinate', style="bar.Horizontal.TProgressbar")
pb_frecuencia_cardiaca.place(
    x=527.0,
    y=597.0,
    width=224.0,
    height=34.0,
)
def fill_progress_saturacion_oxigeno():
    return 50
pb_frecuencia_cardiaca['value'] =  fill_progress_saturacion_oxigeno()

#####################################




#endregion

#region NOTA ACLARATORIA
canvas.create_text(
    837.0,
    359.0,
    anchor="nw",
    text="Nota aclaratoria : ",
    fill="#000000",
    font=("RobotoRoman Regular", 30 * -1)
)
#Aqui debe ir el textbox con el valor de la nota aclaratoria
lbl_nota = Label(
    window,
    text="",
    bd=0,
    bg="#F5F5F5",
    fg="#000716",
    font=("RobotoRoman Regular", 25 * -1)
)
lbl_nota.place(
    x=840.0,
    y=417.0,
    width=356.0,
    height=214.0
)
#endregion

#region BOTON GUARDAR
img_guardar = PhotoImage(
    file=relative_to_assets("button_2.png"))
btn_guardar = Button(
    image=img_guardar,
    borderwidth=0,
    highlightthickness=0,
    command = lambda: print("button_2 clicked"),
    relief="flat"
)
btn_guardar.place(
    x=840.0,
    y=657.0,
    width=431.851318359375,
    height=68.0
)
#endregion

window.resizable(False, False)
window.mainloop()
