
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Angel\Monitor-Fisiologico\interfaces\assets\reporte_med")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1260x725")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 725,
    width = 1260,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
img_regresar = PhotoImage(
    file=relative_to_assets("button_1.png"))
btn_regresar = Button(
    image=img_regresar,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
    bg ="white"
)
btn_regresar.place(
    x=50.0,
    y=16.0,
    width=61.0,
    height=60.0
)
 #LINEA DIVISORIA ENTRE LOGO Y TITULO INFORME
canvas.create_rectangle(
    49.0,
    95.93429565429688,
    1196.0,
    97.0,
    fill="gray",
    outline="")
# LINEA DIVISORIA ENTRE DATOS SUJETO Y MEDIDAS PARAMETROS
canvas.create_rectangle(
    47.0,
    322.0,
    1196.0,
    325.0,
    fill="#000000",
    outline="")

img_logo = PhotoImage(
    file=relative_to_assets("logo1.png"))
logo1 = canvas.create_image(
    1070.0,
    70.0,
    image=img_logo
)

canvas.create_text(
    50.0,
    120.0,
    anchor="nw",
    text="INFORME DE MEDICIÓN",
    fill="#000000",
    font=("RobotoRoman Regular", 30 * -1)
)

canvas.create_text(
    50.0,
    195.0,
    anchor="nw",
    text="Nombre : ",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

canvas.create_text(
    900.0,
    198.0,
    anchor="nw",
    text="Sexo :",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

canvas.create_text(
    600,
    198.0,
    anchor="nw",
    text="Edad : ",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

canvas.create_text(
    600,
    242.60400390625,
    anchor="nw",
    text="Peso :",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

canvas.create_text(
    862.0,
    247.0,
    anchor="nw",
    text="Estatura :",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

canvas.create_text(
    685.0,
    122.0,
    anchor="nw",
    text="Fecha de emisión :",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)


txb_nombre = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_nombre.place(
    x=177.0,
    y=198.0,
    width=388.0,
    height=34.0
)


txb_cod_doc = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_cod_doc.place(
    x=50.0,
    y=247.0,
    width=515.0,
    height=34.0
)


txb_fecha = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_fecha.place(
    x=946.0,
    y=122.0,
    width=250.0,
    height=34.0
)

txb_peso = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_peso.place(
    x=707.6485595703125,
    y=247.0,
    width=108.0,
    height=34.0
)

txb_edad = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_edad.place(
    x=707.6485595703125,
    y=198.0,
    width=108.0,
    height=34.0
)


txb_sexo = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_sexo.place(
    x=985.0,
    y=198.0,
    width=108.0,
    height=34.0
)


txb_estatura = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_estatura.place(
    x=985.0,
    y=247.0,
    width=108.0,
    height=34.0
)


#Aqui se colocara el progress bar para la escala de saturacion de oxigeno
txb_escala_saturacion_oxigeno = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_escala_saturacion_oxigeno.place(
    x=527.0,
    y=478.0,
    width=224.0,
    height=34.0
)

#aqui se colocara el textbox que contiene el valor de la saturacion de oxigeno
txb_valor_saturacion_oxigeno = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_valor_saturacion_oxigeno.place(
    x=379.0,
    y=480.0,
    width=96.0,
    height=34.0
)

canvas.create_text(
    56.0,
    489.0,
    anchor="nw",
    text="Saturación de Oxígeno",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

#Aqui se colora el progress bar para la escala de la temperatura
txb_escala_temp = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_escala_temp.place(
    x=527.0,
    y=415.0,
    width=224.0,
    height=34.0
)

#Aqui debe ir el textbox con el valor de la nota aclaratoria
txb_nota = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_nota.place(
    x=840.0,
    y=417.0,
    width=356.0,
    height=214.0
)

#aqui se colocara el textbox con el valor de la temperatura
txb_valor_temp = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_valor_temp.place(
    x=379.0,
    y=417.0,
    width=96.0,
    height=34.0
)

canvas.create_text(
    162.0,
    424.0,
    anchor="nw",
    text="Temperatura",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

canvas.create_text(
    50.0,
    359.0,
    anchor="nw",
    text="Parámetro Fisiológico",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

canvas.create_text(
    600.0,
    361.0,
    anchor="nw",
    text="Escala",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

canvas.create_text(
    400.0,
    359.0,
    anchor="nw",
    text="Valor",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

#aqui debe ir el progress bar para colocar la frecuencia cardiaca
txb_escala_frecuencia_cardiaca = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_escala_frecuencia_cardiaca.place(
    x=527.0,
    y=597.0,
    width=224.0,
    height=34.0,
)

#aqui va el valor correspondiente a la medicion de la frecuencia cardiaca
txb_valor_frecuencia_cardiaca = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_valor_frecuencia_cardiaca.place(
    x=379.0,
    y=597.0,
    width=96.0,
    height=34.0
)

canvas.create_text(
    70.0,
    608.0,
    anchor="nw",
    text="Frecuencia Cardiaca ",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

#aqui va el progress bar de la presion arterial
txb_escala_presion_arterial = Entry(
    bd=0,
    bg="white",
    state="disabled",
    highlightthickness=0
)
txb_escala_presion_arterial.place(
    x=527.0,
    y=538.0,
    width=224.0,
    height=34.0
)

#aqui va el textbox del valor correspondiente a la presion arterial
txb_valor_presion_arterial = Entry(
    bd=0,
    bg="white",
    fg="#000716",
    state="disabled",
    highlightthickness=0
)
txb_valor_presion_arterial.place(
    x=379.0,
    y=540.0,
    width=96.0,
    height=34.0
)

canvas.create_text(
    137.0,
    549.0,
    anchor="nw",
    text="Presión Arterial ",
    fill="#000000",
    font=("RobotoRoman Regular", 25 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=840.0,
    y=657.0,
    width=431.851318359375,
    height=68.0
)

canvas.create_text(
    837.0,
    359.0,
    anchor="nw",
    text="Nota aclaratoria : ",
    fill="#000000",
    font=("RobotoRoman Regular", 30 * -1)
)
window.resizable(False, False)
window.mainloop()
